name: gamiez
description: "The world of games."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.5.1
  fpdart: ^1.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  percent_indicator: ^4.2.3
  readmore: ^2.2.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/gamiez.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/gamiez.png"